/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VEW;
import MODEL.ModelEmprestimo;
import CONTROLLER.ControllerEmprestimo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sansepiol
 */
public class ViewEmprestimo extends javax.swing.JFrame {

   ModelEmprestimo modelEmprestimo = new ModelEmprestimo();
   ControllerEmprestimo controllerEmprestimo = new ControllerEmprestimo();
   List <ModelEmprestimo> listaEmprestimo = new ArrayList<>();
   String cadAlt="cad";
    
    
    
    public ViewEmprestimo() {
        initComponents();
        carregarEmprestimos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfLivro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfAluno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbConfirmar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jFormattedEmprestimodata = new javax.swing.JFormattedTextField();
        jFormattedDataPrevisao = new javax.swing.JFormattedTextField();
        jFormattedDevolucaoData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(89, 89, 89));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel1.setText("EMPRESTIMOS ");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jLabel3.setText("LIVRO:");

        jLabel4.setBackground(new java.awt.Color(252, 252, 252));
        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jLabel4.setText("ALUNO:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jLabel5.setText("DATA DE EMPRESTIMO:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jLabel6.setText("DATA DE DEVOLUÇÃO:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jLabel7.setText("DATA PREVISTA PARA DEVOLUÇÃO:");

        jTable1.setBackground(new java.awt.Color(172, 247, 255));
        jTable1.setBorder(null);
        jTable1.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "LIVRO", "ALUNO", "DATA EMPRESTIMO", "DATA PREVISTA", "DATA DEVOLUÇÃO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(20);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jbConfirmar.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/ICONS/adicionar.png"))); // NOI18N
        jbConfirmar.setText("CONFIRMAR");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jbDeletar.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/ICONS/pilha-de-tres-livros.png"))); // NOI18N
        jbDeletar.setText("DELETAR");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTIL/ICONS/lapis.png"))); // NOI18N
        jbAlterar.setText("ALTERAR");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        try {
            jFormattedEmprestimodata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedDataPrevisao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedDataPrevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedDataPrevisaoActionPerformed(evt);
            }
        });

        try {
            jFormattedDevolucaoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jtfAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                        .addComponent(jtfLivro)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar))
                    .addComponent(jFormattedEmprestimodata, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedDataPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedDevolucaoData, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedEmprestimodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedDataPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedDevolucaoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbConfirmar)
                            .addComponent(jbDeletar)
                            .addComponent(jbAlterar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
     modelEmprestimo = new ModelEmprestimo();
     modelEmprestimo.setLivro_alugado(jtfLivro.getText());
     modelEmprestimo.setUsu_emprestimo(jtfAluno.getText());
     modelEmprestimo.setData_emprestimo(jFormattedEmprestimodata.getText());
     modelEmprestimo.setData_previsao(jFormattedDataPrevisao.getText());
     modelEmprestimo.setData_devolucao(jFormattedDevolucaoData.getText());
        
        if (cadAlt.equals("cad")) {
            
            
        if (controllerEmprestimo.salvarLivroController(modelEmprestimo)){
            
        JOptionPane.showMessageDialog(this,"O EMPRESTIMO FOI UM SUCESSO!","!",JOptionPane.INFORMATION_MESSAGE);
           LimparCampos();
           carregarEmprestimos();
       }
      
       else {
        JOptionPane.showMessageDialog(this, "ERRO AO SOLICITAR O EMPRESTIMO","!",JOptionPane.ERROR_MESSAGE);
       }
            
            
            
        } else{
            modelEmprestimo.setId_emprestimo(Integer.parseInt(jtfId.getText()));
             if (controllerEmprestimo.atualizarEmprestimoController(modelEmprestimo)){
                  
                 
               
                 
        JOptionPane.showMessageDialog(this,"LIVRO ALTERADO COM SUCESSO!","!",JOptionPane.INFORMATION_MESSAGE);
           
           LimparCampos();
           carregarEmprestimos();
       }
      
       else {
        JOptionPane.showMessageDialog(this, "ERRO AO ALTERAR O LIVRO","!",JOptionPane.ERROR_MESSAGE);
       }
        
        }
  
    

        
        
        
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void LimparCampos(){
    jtfAluno.setText("");
    jtfLivro.setText("");
    jtfId.setText("");
    jFormattedDataPrevisao.setText("");
    jFormattedDevolucaoData.setText("");
    jFormattedEmprestimodata.setText("");
  
    
    }
    
    
     private void carregarEmprestimos(){
           
     listaEmprestimo = controllerEmprestimo.getListaEmprestimoController();
     DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
     modelo.setNumRows(0);
     
     
         for (int i = 0; i < listaEmprestimo.size(); i++) {
             modelo.addRow(new Object[]{
             listaEmprestimo.get(i).getId_emprestimo(),
             listaEmprestimo.get(i).getLivro_alugado(),
             listaEmprestimo.get(i).getUsu_emprestimo(),
             listaEmprestimo.get(i).getData_emprestimo(),
             listaEmprestimo.get(i).getData_previsao(),
             listaEmprestimo.get(i).getData_emprestimo()
                
             
             });
         }
     
     
     }
    
    
    
    private void jFormattedDataPrevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedDataPrevisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedDataPrevisaoActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        int linha = jTable1.getSelectedRow(); 
        
        if (linha < 0){
        JOptionPane.showMessageDialog(this, "USUÁRIO NÃO SELECIONADO!");
        
        }
        
        else {
          int codigo = (int) jTable1.getValueAt(linha, 0);
          controllerEmprestimo.excluirEmprestimoController(codigo);
          carregarEmprestimos();
          LimparCampos();
          JOptionPane.showMessageDialog(this, "USUÁRIO EXCLUIDO COM EXITO!");
        }
        
        
        
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        modelEmprestimo = new ModelEmprestimo();
        cadAlt = "alt";
        
         int linha = jTable1.getSelectedRow(); 
      
        
        if (linha < 0){
        JOptionPane.showMessageDialog(this, "LIVRO NÃO SELECIONADO!");
        
        }
        
        else {
           
          int codigo = (int) jTable1.getValueAt(linha, 0);
          
          controllerEmprestimo.alterarEmprestimoController(codigo);
          jtfId.setText(String.valueOf(modelEmprestimo.getId_emprestimo()));
          jtfLivro.setText(modelEmprestimo.getLivro_alugado());
          jtfAluno.setText(String.valueOf(modelEmprestimo.getUsu_emprestimo()));
          jFormattedEmprestimodata.setText(modelEmprestimo.getData_emprestimo());
          jFormattedDataPrevisao.setText(String.valueOf(modelEmprestimo.getData_previsao()));
          jFormattedDevolucaoData.setText(modelEmprestimo.getData_devolucao());
          
          
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jbAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedDataPrevisao;
    private javax.swing.JFormattedTextField jFormattedDevolucaoData;
    private javax.swing.JFormattedTextField jFormattedEmprestimodata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JTextField jtfAluno;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfLivro;
    // End of variables declaration//GEN-END:variables
}
